import { createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'

// Router factory consumed by TanStack Start on both server and client.
// `routeTree.gen.ts` is generated by the Start Vite plugin from `app/routes/**`
// on the first dev/build run (it is gitignored).
export function getRouter() {
  const router = createRouter({
    routeTree,
    scrollRestoration: true,
    defaultPreload: 'intent',
  })

  return router
}
